import {authorize,initializeProject} from "./google-api.js";
const locations=[];let map,editingId=null;const $=id=>document.getElementById(id),status=(m,t="")=>{$("status").textContent=m;$('status').className=`status ${t}`};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const coord=(v,a,b)=>v!==""&&Number.isFinite(Number(v))&&Number(v)>=a&&Number(v)<=b;
function render(){const q=$("searchInput").value.toLowerCase();const rows=locations.filter(x=>[x.name,x.address,x.description,x.category].join(" ").toLowerCase().includes(q));$("listMeta").textContent=`${rows.length} 個地點`;$("locationList").replaceChildren(...rows.map(x=>{const b=document.createElement("button");b.className="location-card";b.innerHTML=`<strong>${esc(x.name)}</strong><small>${esc(x.address||`${x.latitude}, ${x.longitude}`)}</small>`;b.onclick=()=>{map.setView([x.latitude,x.longitude],15);openForm(x)};return b}))}
function openForm(x){editingId=x?.id||null;$("dialogTitle").textContent=x?"編輯地點":"新增地點";for(const [id,key] of [["name","name"],["address","address"],["description","description"],["category","category"],["latitude","latitude"],["longitude","longitude"]])$(id).value=x?.[key]??"";$("formError").textContent="";$('locationDialog').showModal()}
function save(e){e.preventDefault();const name=$("name").value.trim(),address=$("address").value.trim(),lat=$("latitude").value.trim(),lng=$("longitude").value.trim();if(!name||(!address&&!(coord(lat,-90,90)&&coord(lng,-180,180))))return $("formError").textContent="請填寫名稱，並提供地址或有效座標。";if((lat||lng)&&!(coord(lat,-90,90)&&coord(lng,-180,180)))return $("formError").textContent="座標格式無效。";const now=new Date().toISOString(),v={id:editingId||crypto.randomUUID(),name,address,latitude:Number(lat||23.7),longitude:Number(lng||120.9),description:$("description").value.trim(),category:$("category").value.trim(),createdAt:now,updatedAt:now};const i=locations.findIndex(x=>x.id===v.id);i<0?locations.push(v):locations[i]=v;L.marker([v.latitude,v.longitude]).addTo(map).bindPopup(`<strong>${esc(v.name)}</strong>`);render();$('locationDialog').close();status("地點已儲存","success")}
async function connect(){const b=$("authButton");b.disabled=true;b.textContent="連線中…";try{await authorize();await initializeProject();$("addButton").disabled=false;$("fitButton").disabled=false;b.textContent="Google 環境：已準備";status("Google 環境：授權與能力驗證成功","success")}catch(e){status(`初始化失敗：${e.message}`,"error");b.disabled=false;b.textContent="初始化我的地圖"}}
map=L.map("map").setView([23.7,120.9],8);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap 貢獻者"}).addTo(map);map.on("click",e=>!$("addButton").disabled&&openForm({latitude:e.latlng.lat.toFixed(6),longitude:e.latlng.lng.toFixed(6)}));$("authButton").onclick=connect;$("addButton").onclick=()=>openForm();$("locationForm").onsubmit=save;$("searchInput").oninput=render;$("openSidebar").onclick=()=>$("sidebar").classList.add("is-open");$("closeSidebar").onclick=()=>$("sidebar").classList.remove("is-open");$("fitButton").onclick=()=>locations.length&&map.fitBounds(L.latLngBounds(locations.map(x=>[x.latitude,x.longitude])),{padding:[40,40]});render();
