import {authorize,initializeProject,loadLocations,saveLocation,deleteLocation} from "./google-api.js";
const locations=[];const markers=new Map();let map,editingId=null;const $=id=>document.getElementById(id),status=(m,t="")=>{$("status").textContent=m;$('status').className=`status ${t}`};const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function draw(x){if(markers.has(x.id))markers.get(x.id).remove();const m=L.marker([x.latitude,x.longitude]).addTo(map).bindPopup(`<strong>${esc(x.name)}</strong>`);m.on("click",()=>openForm(x));markers.set(x.id,m)}
function render(){const q=$("searchInput").value.toLowerCase();const rows=locations.filter(x=>[x.name,x.address,x.description,x.category].join(" ").toLowerCase().includes(q));$("listMeta").textContent=`${rows.length} 個地點`;$("locationList").replaceChildren(...rows.map(x=>{const b=document.createElement("button");b.className="location-card";b.innerHTML=`<strong>${esc(x.name)}</strong><small>${esc(x.address||`${x.latitude}, ${x.longitude}`)}</small>`;b.onclick=()=>{map.setView([x.latitude,x.longitude],15);openForm(x)};return b}))}
function openForm(x){editingId=x?.id||null;$("dialogTitle").textContent=x?"編輯地點":"新增地點";for(const [id,key] of [["name","name"],["address","address"],["description","description"],["category","category"],["latitude","latitude"],["longitude","longitude"]])$(id).value=x?.[key]??"";$('locationDialog').showModal()}
async function save(e){e.preventDefault();const name=$("name").value.trim(),address=$("address").value.trim(),lat=$("latitude").value.trim(),lng=$("longitude").value.trim();if(!name)return $("formError").textContent="名稱必填。";if(!address&&!lat&&!lng)return $("formError").textContent="請提供地址或座標。";const latitude=Number(lat),longitude=Number(lng);if((lat||lng)&&(!Number.isFinite(latitude)||!Number.isFinite(longitude)||latitude<-90||latitude>90||longitude<-180||longitude>180))return $("formError").textContent="座標格式無效。";const old=locations.find(x=>x.id===editingId);const v={id:editingId||crypto.randomUUID(),name,address,latitude:lat?latitude:23.7,longitude:lng?longitude:120.9,description:$("description").value.trim(),category:$("category").value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};try{await saveLocation(v);const i=locations.findIndex(x=>x.id===v.id);i<0?locations.push(v):locations[i]=v;draw(v);render();$('locationDialog').close();status("地點已同步至 Google Sheets","success")}catch(error){status(`儲存失敗：${error.message}`,"error")}}
async function connect(){const b=$("authButton");b.disabled=true;b.textContent="連線中…";try{await authorize();await initializeProject();locations.push(...await loadLocations());locations.forEach(draw);render();$("addButton").disabled=false;$("fitButton").disabled=false;b.textContent="Google 環境：已準備";status("Google 環境：授權與能力驗證成功","success")}catch(e){status(`初始化失敗：${e.message}`,"error");b.disabled=false;b.textContent="初始化我的地圖"}}
map=L.map("map").setView([23.7,120.9],8);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap 貢獻者"}).addTo(map);map.on("click",e=>{if(!$('addButton').disabled)openForm({latitude:e.latlng.lat.toFixed(6),longitude:e.latlng.lng.toFixed(6)})});$("authButton").onclick=connect;$("addButton").onclick=()=>openForm();$("locationForm").onsubmit=save;$("searchInput").oninput=render;$("closeSidebar").onclick=()=>$('sidebar').classList.remove('is-open');$("fitButton").onclick=()=>locations.length&&map.fitBounds(L.latLngBounds(locations.map(x=>[x.latitude,x.longitude])),{padding:[40,40]});render();
async function removeCurrent(){if(!editingId||!confirm("確定要刪除這個地點嗎？"))return;try{await deleteLocation(editingId);const i=locations.findIndex(x=>x.id===editingId);if(i>=0)locations.splice(i,1);if(markers.has(editingId)){markers.get(editingId).remove();markers.delete(editingId)}$('locationDialog').close();render();status("地點已刪除","success")}catch(error){status(`刪除失敗：${error.message}`,"error")}}
const deleteButton=document.createElement("button");deleteButton.type="button";deleteButton.className="button button-quiet";deleteButton.textContent="刪除地點";deleteButton.onclick=removeCurrent;document.querySelector(".dialog-actions")?.prepend(deleteButton);
