import {APP_CONFIG} from "./config.js";

const DRIVE="https://www.googleapis.com/drive/v3";
const SHEETS="https://sheets.googleapis.com/v4";
const FOLDER_PROPS={application:"personal-map",projectName:"個人地圖管理工具",resourceRole:"project-root",schemaVersion:"1"};
const CONFIG_PROPS={application:"personal-map",projectName:"個人地圖管理工具",resourceRole:"binding-config",schemaVersion:"1"};
const DB_PROPS={application:"personal-map",projectName:"個人地圖管理工具",resourceRole:"primary-database",schemaVersion:"1"};
let accessToken="";
const headers=()=>({Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"});
async function api(url,options={}){const response=await fetch(url,{...options,headers:{...headers(),...(options.headers||{})}});if(response.status===401)throw new Error("AUTH_EXPIRED");if(!response.ok)throw new Error(`GOOGLE_API_${response.status}`);return response.status===204?null:response.json()}
function q(value){return `'${String(value).replaceAll("'","\\'")}'`}
function query(name,mime,property){return `name = ${q(name)} and mimeType = ${q(mime)} and trashed = false and appProperties has { key = 'application' and value = 'personal-map' } and appProperties has { key = 'resourceRole' and value = ${q(property)} }`}
export function hasToken(){return Boolean(accessToken)}
export async function authorize(){if(!window.google?.accounts?.oauth2)throw new Error("GIS_NOT_LOADED");if(!APP_CONFIG.oauthClientId)throw new Error("OAUTH_CLIENT_ID_MISSING");return new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:APP_CONFIG.oauthClientId,scope:APP_CONFIG.scopes,callback:response=>{if(response.error)reject(new Error("AUTH_DENIED"));else{accessToken=response.access_token;resolve(response)}}});client.requestAccessToken({prompt:"consent"})})}
async function files(search,fields="files(id,name,mimeType,parents,appProperties,createdTime,modifiedTime)"){return api(`${DRIVE}/files?q=${encodeURIComponent(search)}&spaces=drive&includeItemsFromAllDrives=false&supportsAllDrives=false&fields=${encodeURIComponent(fields)}`)}
async function createFile(metadata,media){const form=new FormData();form.append("metadata",new Blob([JSON.stringify(metadata)],{type:"application/json"}));if(media!==undefined)form.append("file",new Blob([media],{type:metadata.mimeType}));const response=await fetch(`${DRIVE}/files?uploadType=multipart&fields=id,name,mimeType,parents,appProperties`,{method:"POST",headers:{Authorization:`Bearer ${accessToken}`},body:form});if(!response.ok)throw new Error(`GOOGLE_API_${response.status}`);return response.json()}
async function findOrCreateFolder(){const found=await files(query(APP_CONFIG.folderName,"application/vnd.google-apps.folder","project-root"));if(found.files.length>1)throw new Error("FOLDER_CONFLICT");if(found.files[0])return found.files[0];return createFile({name:APP_CONFIG.folderName,mimeType:"application/vnd.google-apps.folder",parents:["root"],appProperties:FOLDER_PROPS})}
async function findDatabase(folderId){const found=await files(query(APP_CONFIG.spreadsheetName,"application/vnd.google-apps.spreadsheet","primary-database"));return found.files.filter(file=>file.parents?.includes(folderId))}
async function createDatabase(folderId){
  const spreadsheet=await api(`${SHEETS}/spreadsheets`,{method:"POST",body:JSON.stringify({properties:{title:APP_CONFIG.spreadsheetName}})});
  const database=await api(`${DRIVE}/files/${spreadsheet.spreadsheetId}?addParents=${encodeURIComponent(folderId)}&fields=id,name,mimeType,parents`,{method:"PATCH",body:JSON.stringify({appProperties:DB_PROPS})});
  return database;
}
async function ensureLocations(spreadsheetId){const metadata=await api(`${SHEETS}/spreadsheets/${spreadsheetId}?fields=sheets.properties`);const has=metadata.sheets?.some(sheet=>sheet.properties.title==="Locations");if(!has)await api(`${SHEETS}/spreadsheets/${spreadsheetId}:batchUpdate`,{method:"POST",body:JSON.stringify({requests:[{addSheet:{properties:{title:"Locations"}}}]})});const values=["id","name","address","latitude","longitude","description","category","createdAt","updatedAt"];const existing=await api(`${SHEETS}/spreadsheets/${spreadsheetId}/values/Locations!A1:I1`);if(!existing.values?.length)await api(`${SHEETS}/spreadsheets/${spreadsheetId}/values/Locations!A1:I1?valueInputOption=RAW`,{method:"PUT",body:JSON.stringify({range:"Locations!A1:I1",majorDimension:"ROWS",values:[values]})});}
export async function initializeProject(){const folder=await findOrCreateFolder();let databases=await findDatabase(folder.id);if(databases.length>1)throw new Error("DATABASE_CONFLICT");const database=databases[0]||await createDatabase(folder.id);await ensureLocations(database.id);const now=new Date().toISOString();const config={application:"personal-map",projectName:APP_CONFIG.projectName,schemaVersion:1,folderId:folder.id,spreadsheetId:database.id,createdAt:now,updatedAt:now};const configs=await files(query(APP_CONFIG.configFileName,"application/json","binding-config"));if(!configs.files.length)await createFile({name:APP_CONFIG.configFileName,mimeType:"application/json",parents:[folder.id],appProperties:CONFIG_PROPS},JSON.stringify(config,null,2));return {folder,database,config}}
