import {APP_CONFIG} from "./config.js";

const DRIVE="https://www.googleapis.com/drive/v3";
const SHEETS="https://sheets.googleapis.com/v4";
const FOLDER_PROPS={application:"personal-map",projectName:"個人地圖管理工具",resourceRole:"project-root",schemaVersion:"1"};
const CONFIG_PROPS={application:"personal-map",projectName:"個人地圖管理工具",resourceRole:"binding-config",schemaVersion:"1"};
const DB_PROPS={application:"personal-map",projectName:"個人地圖管理工具",resourceRole:"primary-database",schemaVersion:"1"};
let accessToken="";
let databaseId="";
const headers=()=>({Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"});
async function api(url,options={}){const response=await fetch(url,{...options,headers:{...headers(),...(options.headers||{})}});if(response.status===401)throw new Error("AUTH_EXPIRED");if(!response.ok){const body=await response.text();let detail=body;try{const parsed=JSON.parse(body);detail=parsed.error?.message||body}catch{}throw new Error(`GOOGLE_API_${response.status}: ${detail.slice(0,240)}`)}return response.status===204?null:response.json()}
function q(value){return `'${String(value).replaceAll("'","\\'")}'`}
function query(name,mime){return `name=${q(name)} and mimeType=${q(mime)} and trashed=false`}
export function hasToken(){return Boolean(accessToken)}
export async function loadLocations(){const result=await api(`${SHEETS}/spreadsheets/${databaseId}/values/${encodeURIComponent("Locations!A2:I")}`);return (result.values||[]).map(row=>({id:row[0]||"",name:row[1]||"",address:row[2]||"",latitude:Number(row[3]),longitude:Number(row[4]),description:row[5]||"",category:row[6]||"",createdAt:row[7]||"",updatedAt:row[8]||""})).filter(x=>x.id)}
export async function saveLocation(location){const rows=await loadLocations();const index=rows.findIndex(x=>x.id===location.id);const row=[location.id,location.name,location.address,String(location.latitude),String(location.longitude),location.description,location.category,location.createdAt,location.updatedAt];const target=index<0?rows.length+2:index+2;await api(`${SHEETS}/spreadsheets/${databaseId}/values/${encodeURIComponent(`Locations!A${target}:I${target}`)}?valueInputOption=RAW`,{method:"PUT",body:JSON.stringify({range:`Locations!A${target}:I${target}`,majorDimension:"ROWS",values:[row]})});return location}
export async function deleteLocation(id){const rows=await loadLocations();const index=rows.findIndex(x=>x.id===id);if(index<0)return;const rowNumber=index+2;await api(`${SHEETS}/spreadsheets/${databaseId}/values/${encodeURIComponent(`Locations!A${rowNumber}:I${rowNumber}`)}:clear`,{method:"POST",body:JSON.stringify({})});}
async function step(label,fn){try{return await fn()}catch(error){throw new Error(`${label}：${error.message}`)}}
export async function authorize(){if(!window.google?.accounts?.oauth2)throw new Error("GIS_NOT_LOADED");if(!APP_CONFIG.oauthClientId)throw new Error("OAUTH_CLIENT_ID_MISSING");return new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:APP_CONFIG.oauthClientId,scope:APP_CONFIG.scopes,callback:response=>{if(response.error)reject(new Error("AUTH_DENIED"));else{accessToken=response.access_token;resolve(response)}}});client.requestAccessToken({prompt:"consent"})})}
async function files(search,fields="files(id,name,mimeType,parents,appProperties,createdTime,modifiedTime)"){return api(`${DRIVE}/files?q=${encodeURIComponent(search)}&spaces=drive&includeItemsFromAllDrives=false&supportsAllDrives=false&fields=${encodeURIComponent(fields)}`)}
async function createFile(metadata,media){
  if(media===undefined)return api(`${DRIVE}/files?fields=id,name,mimeType,parents,appProperties`,{method:"POST",body:JSON.stringify(metadata)});
  const file=await api(`${DRIVE}/files?fields=id,name,mimeType,parents,appProperties`,{method:"POST",body:JSON.stringify(metadata)});
  const response=await fetch(`${DRIVE}/files/${file.id}?uploadType=media&fields=id,name,mimeType,parents,appProperties`,{method:"PATCH",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":metadata.mimeType},body:media});
  if(!response.ok){const body=await response.text();let detail=body;try{detail=JSON.parse(body).error?.message||body}catch{}throw new Error(`GOOGLE_API_${response.status}: ${detail.slice(0,240)}`)}return response.json()
}
function tagged(files,role){return files.filter(file=>file.appProperties?.application==="personal-map"&&file.appProperties?.resourceRole===role)}
async function findOrCreateFolder(){const found=tagged((await files(query(APP_CONFIG.folderName,"application/vnd.google-apps.folder"))).files,"project-root");if(found.length>1)throw new Error("FOLDER_CONFLICT");if(found[0])return found[0];return createFile({name:APP_CONFIG.folderName,mimeType:"application/vnd.google-apps.folder",parents:["root"],appProperties:FOLDER_PROPS})}
async function findDatabase(folderId){const found=tagged((await files(query(APP_CONFIG.spreadsheetName,"application/vnd.google-apps.spreadsheet"))).files,"primary-database");return found.filter(file=>file.parents?.includes(folderId))}
async function createDatabase(folderId){
  const spreadsheet=await api(`${SHEETS}/spreadsheets`,{method:"POST",body:JSON.stringify({properties:{title:APP_CONFIG.spreadsheetName}})});
  const database=await api(`${DRIVE}/files/${spreadsheet.spreadsheetId}?addParents=${encodeURIComponent(folderId)}&removeParents=root&fields=id,name,mimeType,parents,appProperties`,{method:"PATCH",body:JSON.stringify({appProperties:DB_PROPS})});
  return database;
}
async function ensureLocations(spreadsheetId){const metadata=await api(`${SHEETS}/spreadsheets/${spreadsheetId}?fields=sheets(properties)`);const has=metadata.sheets?.some(sheet=>sheet.properties.title==="Locations");if(!has)await api(`${SHEETS}/spreadsheets/${spreadsheetId}:batchUpdate`,{method:"POST",body:JSON.stringify({requests:[{addSheet:{properties:{title:"Locations"}}}]})});const values=["id","name","address","latitude","longitude","description","category","createdAt","updatedAt"];const existing=await api(`${SHEETS}/spreadsheets/${spreadsheetId}/values/${encodeURIComponent("Locations!A1:I1")}`);if(!existing.values?.length)await api(`${SHEETS}/spreadsheets/${spreadsheetId}/values/${encodeURIComponent("Locations!A1:I1")}?valueInputOption=RAW`,{method:"PUT",body:JSON.stringify({range:"Locations!A1:I1",majorDimension:"ROWS",values:[values]})});}
export async function initializeProject(){const folder=await step("第1步：尋找或建立 Drive 專案資料夾",findOrCreateFolder);let databases=await step("第2步：尋找既有 Google Sheets",()=>findDatabase(folder.id));if(databases.length>1)throw new Error("第2步：DATABASE_CONFLICT");const database=databases[0]||await step("第3步：建立 Google Sheets",()=>createDatabase(folder.id));databaseId=database.id;await step("第4步：建立或確認 Locations 工作表與標題列",()=>ensureLocations(database.id));const now=new Date().toISOString();const config={application:"personal-map",projectName:APP_CONFIG.projectName,schemaVersion:1,folderId:folder.id,spreadsheetId:database.id,createdAt:now,updatedAt:now};const configs=tagged((await step("第5步：尋找設定檔",()=>files(query(APP_CONFIG.configFileName,"application/json")))).files,"binding-config");if(!configs.length)await step("第6步：建立設定 JSON",()=>createFile({name:APP_CONFIG.configFileName,mimeType:"application/json",parents:[folder.id],appProperties:CONFIG_PROPS},JSON.stringify(config,null,2)));return {folder,database,config}}
